routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Front\FrontController@main');

// Common
Route::group(['prefix' => 'common', 'as' => 'common.', 'namespace' => 'Common'], function(){

    Route::get('redirectToLoginPageWithMessage', 'CommonController@redirectToLoginPageWithMessage')->name('redirectToLoginPageWithMessage');

});

// Route group for front page
Route::group(['prefix' => 'front', 'as' => 'front.', 'namespace' => 'Front'], function(){

    Route::get('getFrontTribes', 'FrontController@getFrontTribes')->name('getFrontTribes');
    Route::get('moreTribeSearch', 'FrontController@moreTribeSearchForm')->name('moreTribeSearch');
    Route::get('projectSearchPage', 'FrontController@projectSearchPage')->name('projectSearchPage');
    Route::get('searchProject', 'FrontController@searchProject')->name('searchProject');
    Route::get('viewProject', 'FrontController@viewProject')->name('viewProject');
    Route::get('contact', 'FrontController@contactPage')->name('contact');
    Route::get('aboutus', 'FrontController@aboutUs')->name('aboutus');
    Route::get('gettingStarted', 'FrontController@gettingStarted')->name('gettingStarted');

    Route::post('sendMessage', 'FrontController@sendMessage')->name('sendMessage');

});




// Route group for login page
Route::group(['prefix' => 'auth', 'as' => 'auth.', 'namespace' => 'Auth'], function () {

    //Users auth control
    Route::get('registrationForm', 'RegisterController@registrationForm')->name('registrationForm');
    Route::post('register', 'RegisterController@register')->name('register');


    //Login control
    Route::get('loginForm', 'LoginController@loginForm')->name('loginForm');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::post('login', 'LoginController@login')->name('login');

    // Route::get('users/{user}', 'UserController@show')->name('users.show');
    // Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    // Route::put('users/{user}', 'UserController@update')->name('users.update');
    // Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    // Route::get('permissions', 'PermissionController@index')->name('permissions');
    // Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
});

Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function(){

    Route::get('user-detail', 'UserController@userDetail')->name('user-detail');
    Route::post('sendMessage', 'UserController@sendMessage')->name('sendMessage');



    Route::middleware(['logincheck'])->group(function () {
        Route::get('profile-page', 'UserController@profilePage')->name('profile-page');
        Route::get('project-list-page', 'UserController@projectListPage')->name('project-list-page');
        Route::get('message-list-page', 'UserController@messageListPage')->name('message-list-page');


        Route::post('profile-update', 'UserController@profileUpdate')->name('profile-update');
        Route::post('message-mark-as-read', 'UserController@messageMarkAsRead')->name('message-mark-as-read');

    });
});

Route::group(['prefix' => 'tribe', 'as' => 'tribe.', 'namespace' => 'Tribe'], function(){
    Route::get('main', 'TribeController@mainPage')->name('main');
    Route::get('getTribePostings', 'TribeController@getTribePostings')->name('getTribePostings');
    Route::get('searchTribeFull', 'TribeController@searchTribeFull')->name('searchTribeFull');

    /**
     * Tribe functions that require login check.
     */
    Route::middleware(['logincheck'])->group(function () {
        Route::get('createForm', 'TribeController@createTribeForm')->name('createForm');
        Route::get('createPostingForm', 'TribeController@createPostingForm')->name('createPostingForm');
        Route::get('createProjectForm', 'TribeController@createProjectForm')->name('createProjectForm');
        Route::get('setting-main', 'TribeController@settingMain')->name('setting-main');
        Route::get('setting-profile', 'TribeController@settingMain')->name('setting-profile');


        Route::post('createPosting', 'TribeController@createPosting')->name('createPosting');
        Route::post('updatePosting', 'TribeController@updatePosting')->name('updatePosting');
        Route::post('deletePosting', 'TribeController@deletePosting')->name('deletePosting');

        Route::post('createTribe', 'TribeController@createTribe')->name('createTribe');
        Route::post('createProject', 'TribeController@createProject')->name('createProject');


        /**
         * Tribe setting functions (still need login check)
         */
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function(){
            Route::get('main', 'TribeSetController@settingMain')->name('main');
            Route::get('profile-edit', 'TribeSetController@profileEditForm')->name('profile-edit');
            Route::get('join-request', 'TribeSetController@joinRequest')->name('join-request');
            Route::get('project-list', 'TribeSetController@projectList')->name('project-list');

            Route::post('profile-update', 'TribeSetController@profileUpdate')->name('profile-update');

            Route::post('join-decline', 'TribeSetController@declineJoin')->name('join-decline');
            Route::post('join-accept', 'TribeSetController@acceptJoin')->name('join-accept');


        });

    });

    /**
     * Tribe functions that require login check for ajax calls.
     *
     */
    Route::middleware(['logincheck_ajax'])->group(function () {
        Route::post('requestJoin', 'TribeController@requestJoin')->name('requestJoin');
        Route::post('projectJoinRequest', 'TribeController@projectJoinRequest')->name('projectJoinRequest');
    });

});

app/Http/Controllers/Tribe/TribeController.php
<?php

namespace App\Http\Controllers\Tribe;

use App\Helper\TribeHelper;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Log;

class TribeController extends Controller
{

    /**
     * TribeController constructor.
     */
    public function __construct()
    {
//        $this->middleware('guest');
    }



    /**
     * move to tribe create form
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function createTribeForm(Request $request){

        //Get area of interest from the config file.
        // config/code.php
        $interests = Config::get('code.interests');

        return view('pages.tribe.create', ["interests"=>$interests]);
    }

    /**
     * Create tribe
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function createTribe(Request $request){

        $this->validator($request->all())->validate();

        //when validated
        $tribe_id = uniqid(date("Ymd"));
        $name = $request['name'];
        $summary = $request['summary'];
        $topic1 = $request['topic1'];
        $topic2 = $topic1;
        $region = $request['region'];
        $country = 'Australia'; //$request['country'];
        $created_by = $request->session()->get('email');


        DB::insert('INSERT INTO tribe
                 (ID, NAME, SUMMARY, TOPIC1, TOPIC2, REGION, COUNTRY, CREATED_BY)
                 VALUES
                 (?,?,?,?,?,?,?,?)', [$tribe_id, $name, $summary, $topic1, $topic2, $region, $country, $created_by]);

        $insertObject = array(
            "tribe_id" => $tribe_id,
            "member_id" => $created_by,
        );

        //Add this person into the tribe
        TribeHelper::insertNewMemberIntoTribe($insertObject);
        $tribe = TribeHelper::getTribeMainContentsByTribeId($tribe_id);
        $tribe['isTribeMember']  = TribeHelper::checkIfTribeMember(TribeHelper::getTribeMembers($tribe_id), $created_by);

        return view('pages.tribe.main', ["tribe"=>$tribe]);
    }

    /**
     * Visit a tribe.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function mainPage(Request $request){


        $tribeId = $request['tribe_id'];
        $tribe = TribeHelper::getTribeMainContentsByTribeId($tribeId);

        $userId = $request->session()->get('email');
        $tribe['isTribeMember']  = TribeHelper::checkIfTribeMember(TribeHelper::getTribeMembers($tribeId), $userId);

        return view('pages.tribe.main', ["tribe"=>$tribe]);
    }

    /**
     * Go to tribe posting form page.
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function createPostingForm(Request $request){

        $tribeId = $request['tribeId'];
        $tribe = TribeHelper::getTribeMainContentsByTribeId($tribeId);

        $userId = $request->session()->get('email');
        $tribe['isTribeMember']  = TribeHelper::checkIfTribeMember(TribeHelper::getTribeMembers($tribeId), $userId);

        return view('pages.tribe.create-posting', ["tribe"=>$tribe]);
    }

    /**
     * Go to project creation form page.
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function createProjectForm(Request $request){

        $tribeId = $request['tribeId'];
        $tribe = TribeHelper::getTribeMainContentsByTribeId($tribeId);

        $userId = $request->session()->get('email');
        $tribe['isTribeMember']  = TribeHelper::checkIfTribeMember(TribeHelper::getTribeMembers($tribeId), $userId);

        $interests = Config::get('code.interests');

        return view('pages.tribe.create-project', ["tribe"=>$tribe, "interests"=>$interests]);
    }

    /**
     * Create posting
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function createPosting(Request $request){

        $tribeId = $request['tribeId'];
        $userId = $request->session()->get('email');

        $content = $request['content'];

        DB::insert('INSERT INTO tribe_posting
                 (TRIBE_ID, CONTENT, CREATED_BY)
                 VALUES
                 (?,?,?)', [$tribeId, $content, $userId]);

        $postings = DB::select('SELECT post.id, post.tribe_id, post.content, post.created_by, user.name as user_name, post.created_at
                    FROM tribe_posting post, users user
                    WHERE post.created_by = user.email
                    AND tribe_id = (?)
                    ORDER BY created_at DESC', [$tribeId]);

        return response($postings);
    }

    /**
     * Update posting
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function updatePosting(Request $request){

        $postId = $request['postId'];
        $tribeId = $request['tribeId'];
        $content = $request['content'];

        DB::update('UPDATE tribe_posting
                    SET
                        content = (?),
                        updated_at = NOW()
                    WHERE
                        id = (?)', [$content, $postId]);

        $postings = DB::select('SELECT post.id, post.tribe_id, post.content, post.created_by, user.name as user_name, post.created_at
                    FROM tribe_posting post, users user
                    WHERE post.created_by = user.email
                    AND tribe_id = (?)
                    ORDER BY created_at DESC', [$tribeId]);

        return response($postings);
    }

    /**
     * [deletePosting description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function deletePosting(Request $request){
        $postId = $request['postId'];
        $tribeId = $request['tribeId'];

        DB::table('tribe_posting')->where('id', '=', $postId)->delete();

        $postings = DB::select('SELECT post.id, post.tribe_id, post.content, post.created_by, user.name as user_name, post.created_at
                    FROM tribe_posting post, users user
                    WHERE post.created_by = user.email
                    AND tribe_id = (?)
                    ORDER BY created_at DESC', [$tribeId]);

        return response($postings);
    }
    /**
     * Get tribe postings
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function getTribePostings(Request $request){

        $tribeId = $request['tribeId'];
        $postings = DB::select('SELECT post.id, post.tribe_id, post.content, post.created_by, user.name as user_name, post.created_at
                    FROM tribe_posting post, users user
                    WHERE post.created_by = user.email
                    AND tribe_id = (?)
                    ORDER BY created_at DESC', [$tribeId]);
        return response($postings);
    }

    /**
     * Create a project
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function createProject(Request $request){

        $title = $request['title'];
        $description = $request['description'];
        $member_no = $request['member_no'];
        $topic = $request['topic'];
        $location = $request['location'];
        $tribeId = $request['tribe_id'];
        $userId = $request->session()->get('email');

        $project_id = DB::table('tribe_project')->insertGetId(
            ['title' => $title, 'description' => $description,
             'member_no' => $member_no, 'topic' =>  $topic,
             'location' => $location, 'country' => 'Australia',
              'created_by' => $userId, 'tribe_id' => $tribeId]
        );


        DB::insert('INSERT INTO member_project
                    (project_id, user_id, status)
                    VALUES
                    (?,?,?)', [$project_id, $userId, '1']);

        $tribeId = $request['tribe_id'];
        $tribe = TribeHelper::getTribeMainContentsByTribeId($tribeId);

        $userId = $request->session()->get('email');
        $tribe['isTribeMember']  = TribeHelper::checkIfTribeMember(TribeHelper::getTribeMembers($tribeId), $userId);

        return view('pages.tribe.main', ["tribe"=>$tribe]);
    }



    /**
     * Get random 25 tribes and move to tribe search page.
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function searchTribeFull(Request $request){

        $interest = $request['interest'];
        $area = $request['area'];

        $query = DB::table('tribe')
                    ->select(DB::raw('id, name, summary,
                                      topic1, topic2, image1,
                                      region, country,
                                      (SELECT COUNT(user_id) FROM tribe_member WHERE tribe_id = id AND active = "Y") AS member_no') );
        if($interest != ''){
            $query->where('topic1', $interest);
        }

        if($area != ''){
            $query->where('region', $area);
        }

        if($interest == '' && $area == ''){
            $query->inRandomOrder();
        }

        $tribes = $query->get();

        $interests = Config::get('code.interests');

        return view('pages.front.tribe-search', ['tribes' => $tribes, "interests" => $interests]);
    }


    /**

resources/views/pages/tribe/create-posting.blade.php
@extends('layouts.tribe')
@section('title', 'Write Posting')
@section('body-content')
<script src="/ckeditor/ckeditor.js"></script>
<style type="text/css">
	body{
		background: #141E30;  /* fallback for old browsers */
		background: -webkit-linear-gradient(to right, #243B55, #141E30);  /* Chrome 10-25, Safari 5.1-6 */
		background: linear-gradient(to right, #243B55, #141E30); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
	}
	.col-md-10 .posting-inputs{
		margin: auto;
	}

	#posting-title{
		width: 40%;
	}
	.form-horizontal .form-group{
        margin-top: 3%;
        margin-right: 0px;
        margin-left: 0px;
        margin-bottom: 2%;
    }
    #write-post-btn{
    	width: 10%;
    	margin-top: 2%;
    }
</style>
<div class="container-fluid">
	<div class="col-md-1"></div>
	<div class="col-md-10 posting-inputs">
		<h1 style="text-align: center; color: white;">Write new posting</h1>
	    <form class="form-horizontal" method="post" id="posting-form" action="{{ route('tribe.createPosting') }}">
	    {{ csrf_field() }}
		    <div class="form-group">
		        <input type="text" id="posting-title" name="posting-title" placeholder="Title of the posting" class="form-control" maxlength="128" required/>
		    </div>
			<div class="form-group editor" id="editor">
				<h1>Hello world!</h1>
			</div>
			<input id="tribeId" name="tribeId" value="{{$tribe['tribe']->id}}" hidden/>
			<a id="write-post-btn" class="btn btn-primary">Submit</a>
		</form>
	</div>
	<div class="col-md-1"></div>
</div>
<script type="text/javascript">
CKEDITOR.replace( 'editor', {
    language: 'en',
    // uiColor: '#76706F',
    width: '100%',
    height: '300px'
});

$(document).ready(function(){

	// $("#write-post-btn").click(function(){

	// 	//validateContents();
	// 	var title = $("#posting-title").value;
	// 	var body = CKEDITOR.instances.editor.getData();

	// 	if(title == ''){
	// 		$("#posting-title").attr('placeholder', "Please fill up the title");
	// 	}

	// 	if(body == ''){

	// 	}

	// 	var data = {
	// 		'title': title,
	// 		'body': body
 //        };

 //        alert(CKEDITOR.instances.editor.getData());
 //        return;
 //        $.ajax({
 //            method: "POST",
            // url: '{{Route("tribe.createPosting")}}',
 //            data: data
 //        })
 //        .done(function(tribes){
 //            // display(tribes);
 //        });

	// });

});
</script>
@endsection

resources/views/pages/tribe/main.blade.php
@extends('layouts.tribe')
@section('title', 'Tribe Main')
@section('body-content')
<style type="text/css">
  .col-md-3.left{
    padding: 3%;
    text-align: center;
  }

  .list-group-item-heading.member-heading{
    text-align: center;
    margin-bottom: 10%;
    margin-top: 10%;
  }
  .col-md-12.post-project-div{
    z-index: 3;
    margin-bottom: 1%;
  }
  #write-post-btn{
    width: 60%;
    margin-top: 10%;
  }
  #create-project-btn{
    width: 60%;
    margin-top: 2%;
  }
  .col-md-12.editor{
    padding-left: 5px;
    padding-right: 5px;
  }

</style>

<script type="text/javascript">
  
  var editorCNT = 0;

  $(document).ready(function(){

    getTribePostings();

    $("#write-post-btn").click(function(){

      if(editorCNT > 0 ){
        return;
      }

      var editorHTML = '<div class="col-md-12 editor" id="new-editor-div">'
      editorHTML += '<div id="editor" contenteditable="true" style="border: .25rem solid; border-color: #5bc0de;" onfocusout="editorFocusOut();">'
      editorHTML += '<h2>Put your title</h2>';
      editorHTML += '<p>Write your content</p>'
      editorHTML += '</div>';
      var saveBTN = '<div class="col-md-12" align="right">';
      saveBTN += '<a type="button" id="save-post-btn" class="btn btn-danger" onclick="submitPost()">Save</a>';
      saveBTN += '<hr>';
      saveBTN += '</div>';
      editorHTML += saveBTN;
      editorHTML += '</div>';
      $("#blog-post-div").prepend(editorHTML);

      CKEDITOR.inline('editor');
      $('#edit').focus();

      editorCNT++;
    });
  });

  /**
   * Remove editor if it contains nothing.
   * @return {[type]} [description]
   */
  function removeEditorIfNull(){
    var text = $("#editor").text();
    if(text.trim() == ''){
      $("#new-editor-div").remove();
      editorCNT = 0;
      return;
    } 
  }

  /**
   * When it focuses out of editor.
   * 
   * @return {[type]} [description]
   */
  function editorFocusOut(){
    removeEditorIfNull();
  }

  /**
   * Submit post ajax
   * 
   * @param  {[type]} index [description]
   * @return {[type]}       [description]
   */
  function submitPost(){

      var content = CKEDITOR.instances.editor.getData();

      removeEditorIfNull();

      var data = {
        'content' : content,
        'tribeId' : '{{$tribe['tribe']->id}}'
      };
      $.ajax({
            method: "POST",
            headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
            url: '{{Route("tribe.createPosting")}}',
            data: data
      })
      .done(function(response){
        editorCNT = 0;
        displayTribePostings(response);
      })
      .fail(function() {
        location.reload();
      });
  }

  /**
   * Get tribe postings
   * 
   * @return {[type]} [description]
   */
  function getTribePostings(){

    var data = {
      'tribeId' : '{{$tribe['tribe']->id}}'
    };

    $.ajax({
            method: "GET",
            url: '{{Route("tribe.getTribePostings")}}',
            data: data
      })
      .done(function(response){
        displayTribePostings(response);
      })
  }

  function displayTribePostings(postingList){
    var postHTML = '';
    var date;
    var wordCount = 0;

    postingList.forEach(function(item){
      date = new Date(item.created_at);  
      postHTML += '<div class="tribe-posting-div">';
      postHTML += '<p class="blog-post-meta">'+date.toLocaleDateString("en-AU")+'<a href="#"> '+item.user_name+'</a>';
      if('{{Session::get('email')}}' == item.created_by){
        postHTML += '<a href="#" style="margin-left:70%;" onclick="editPost('+item.id+');">Edit</a>';
      }
      postHTML += '</p>';
      postHTML += '<div id="postbody'+item.id+'" contenteditable="false">';
      postHTML += item.content;
      postHTML += '</div>';

      postHTML += '<div class="col-md-12" id="edit-save-btn-div-'+item.id+'" align="right" style="margin-bottom: 5%;" hidden>';
      postHTML += '<a type="button" id="edit-del-post-btn" class="btn btn-danger" style="margin-right: 1%;" onclick="checkDelete('+item.id+')">Delete</a>';
      postHTML += '<a type="button" id="edit-save-post-btn" class="btn btn-primary" onclick="editPostSave('+item.id+')">Save</a>';
      postHTML += '</div>'

      postHTML += '</div>';
      postHTML += '<hr>';
    });
    $('#blog-post-div').html(postHTML);
  }

  function editPost(postId){
    
    var editpostid = 'postbody' + postId;
    $('#'+editpostid).attr("contenteditable", true);
    CKEDITOR.inline(editpostid);
    $('#edit-save-btn-div-' + postId).show();
    $('#'+editpostid).focus();
  }

  /**
   * Edited post save
   * 
   * @param  {[type]} postId [description]
   * @return {[type]}        [description]
   */
  function editPostSave(postId){
    var editorname = 'postbody'+postId;
    var content = CKEDITOR.instances[editorname].getData();

    var data = {
      'content' : content,
      'postId' : postId,
      'tribeId' : '{{$tribe['tribe']->id}}'
    };
    
    $.ajax({
          method: "POST",
          headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
          url: '{{Route("tribe.updatePosting")}}',
          data: data
    })
    .done(function(response){
      editorCNT = 0;
      displayTribePostings(response);
    })
    .fail(function() {
      location.reload();
    });
  }

  /**
   * Before deleting a post.
   * 
   * @param  {[type]} postId [description]
   * @return {[type]}        [description]
   */
  function checkDelete(postId){
    $('#messageModalBody').text("Do you want to delete the post?");
    $('#confirmBtn').attr('onclick', 'confirmClicked("'+postId+'");');
    $('#messageModal').modal('show');
  }

  /**
   * To delete a post.
   * 
   * @param  {[type]} postId [description]
   * @return {[type]}        [description]
   */
  function confirmClicked(postId){
    $('#messageModal').modal('hide');
    var data = {
      'postId' : postId,
      'tribeId' : '{{$tribe['tribe']->id}}'
    };
    
    $.ajax({
          method: "POST",
          headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
          url: '{{Route("tribe.deletePosting")}}',
          data: data
    })
    .done(function(response){
      editorCNT = 0;
      displayTribePostings(response);
    })
    .fail(function() {
      location.reload();
    });
  }

  function checkSendMessage(){
    $('#messageModalBody').text("Do you want to send the message?");
    $('#confirmBtn').attr('onclick', 'confirmSendClicked();');
    $('#messageModal').modal('show');
  }


  function confirmSendClicked(){
    var message = $("#message-text").val();
    var recipient = $("#recipient-id").val();
    var data = {
      'recipient' : recipient,
      'message' : message
    };

    $('#messageModal').modal('hide');

    $.ajax({
          method: "POST",
          headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
          url: '{{Route("user.sendMessage")}}',
          data: data
    })
    .done(function(response){
      displaySuccess('Your message has successfully been sent.');
    })
    .fail(function() {
      displayFail('Message delivery has failed. Please contact administrator.');
    });
  }


  function displaySuccess(message){
    $('#resultMessageModalBody').text(message);
    $('#resultMessageModal').modal('show');
    $('#memberModal').modal('hide');

    $("#collapseTwo").attr("class", "collapse");
  }

  function displayFail(message){
    $('#resultMessageModalBody').text(message);
    $('#resultMessageModal').modal('show');
    $('#memberModal').modal('hide');
  }

</script>

  {{-- Left pane --}}
  <div class="col-md-3 left" style="border-right: 1px solid; align-items: center;">
  <img data-src="holder.js/200x200" class="img-thumbnail" alt="200x200" style="width: 200px; height: 200px;" src="/images/person_3.jpg" data-holder-rendered="true">
  {{-- <h2 class="profile-name">{{ $tribe['members'][0]->user_name}}</h2> --}}
  <h5 style="font-size: 15px; text-align: left;">{{ $tribe['tribe']->summary}}</h5>
  @if ($tribe['isTribeMember'])
  <div class="col-md-12">
  <a type="button" id="write-post-btn" class="btn btn-primary">Write Posting</a>
  {{-- <a href="{{ route('tribe.createPostingForm', ['tribeId' => $tribe['tribe']->id] ) }}" type="button" id="write-post-btn" class="btn btn-primary">Write Posting</a> --}}
  </div>
  <div class="col-md-12"> 
  <a href="{{ route('tribe.createProjectForm', ['tribeId' => $tribe['tribe']->id] ) }}" type="button" id="create-project-btn" class="btn btn-success">Create Project</a>
  </div>
  @elseif(Session::get('userCreatedTribesCount') == 0)
  <button type="submit" class="btn btn-success" onclick="requestJoin();">Request Join</button>
  @endif
  </div>
  <div class="col-md-6" style="border-right: 1px solid;">
    <div class="blog-post" id="blog-post-div" style="overflow-y: scroll; height: 100vh;">

    </div>
  </div>
  <div class="col-md-3">
    <div class="list-group">
      <h4 class="list-group-item-heading member-heading">Tribe Members</h4>
      <p class="list-group-item-text"></p>
      @foreach ($tribe['members'] as $member)
      <div class="list-group-item" style="padding-bottom: 70px; padding-top: 10px;">
        <div class="col-md-4">
          <img class="img-thumbnail" alt="60x60" style="width: 60px; height: 60px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLdb4IzWVmXx1l2HcR4q1ACeR3eZvDdOB_7wecoQbpjsWhRezgjQX19B8">
        </div>
        <div class="col-md-8">
          <h4 class="list-group-item-heading"><a href="#" onclick="onMemberClick('{{$member->user_id}}')")>{{$member->user_name}}</a></h4>
          <p class="list-group-item-text">{{$member->member_type_name}}</p>
        </div>
      </div>
      @endforeach
    </div>
  </div>
  <!-- Modal for message -->
  <div class="modal fade" id="tribeModal" tabindex="-1" role="dialog" aria-labelledby="tribeModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="tribeModalLabel"></h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div id="tribeModalMessage" class="modal-body">
          .
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  @include('pages.sections.member-modal')
  @include('pages.sections.modal')
<script src="/ckeditor/ckeditor.js"></script>
<script type="text/javascript">
CKEDITOR.disableAutoInline = true;

  function requestJoin(){

    var tribeId = '{{$tribe['tribe']->id}}';
    var data = {
      "tribe_id" : tribeId
    };

    $.ajax({
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      },
      method: "POST",
      url: '{{ route('tribe.requestJoin') }}',
      data: data
    }).done(function(result) {
      //When not logged in.
      if(result.status == 'unauthed'){
        window.location.href = '{{route('auth.loginForm')}}';
      }else{
        $("#tribeModalLabel").text("Join request");
        $("#tribeModalMessage").text(result.message);
        $("#tribeModal").modal('show');
      }
    });
  }

</script>
@endsection 