routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Front\FrontController@main');

// Common
Route::group(['prefix' => 'common', 'as' => 'common.', 'namespace' => 'Common'], function(){

    Route::get('redirectToLoginPageWithMessage', 'CommonController@redirectToLoginPageWithMessage')->name('redirectToLoginPageWithMessage');

});

// Route group for front page
Route::group(['prefix' => 'front', 'as' => 'front.', 'namespace' => 'Front'], function(){

    Route::get('getFrontTribes', 'FrontController@getFrontTribes')->name('getFrontTribes');
    Route::get('moreTribeSearch', 'FrontController@moreTribeSearchForm')->name('moreTribeSearch');
    Route::get('projectSearchPage', 'FrontController@projectSearchPage')->name('projectSearchPage');
    Route::get('searchProject', 'FrontController@searchProject')->name('searchProject');
    Route::get('viewProject', 'FrontController@viewProject')->name('viewProject');
    Route::get('contact', 'FrontController@contactPage')->name('contact');
    Route::get('aboutus', 'FrontController@aboutUs')->name('aboutus');
    Route::get('gettingStarted', 'FrontController@gettingStarted')->name('gettingStarted');

    Route::post('sendMessage', 'FrontController@sendMessage')->name('sendMessage');

});




// Route group for login page
Route::group(['prefix' => 'auth', 'as' => 'auth.', 'namespace' => 'Auth'], function () {

    //Users auth control
    Route::get('registrationForm', 'RegisterController@registrationForm')->name('registrationForm');
    Route::post('register', 'RegisterController@register')->name('register');


    //Login control
    Route::get('loginForm', 'LoginController@loginForm')->name('loginForm');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::post('login', 'LoginController@login')->name('login');

    // Route::get('users/{user}', 'UserController@show')->name('users.show');
    // Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    // Route::put('users/{user}', 'UserController@update')->name('users.update');
    // Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    // Route::get('permissions', 'PermissionController@index')->name('permissions');
    // Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
});

Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function(){

    Route::get('user-detail', 'UserController@userDetail')->name('user-detail');
    Route::post('sendMessage', 'UserController@sendMessage')->name('sendMessage');



    Route::middleware(['logincheck'])->group(function () {
        Route::get('profile-page', 'UserController@profilePage')->name('profile-page');
        Route::get('project-list-page', 'UserController@projectListPage')->name('project-list-page');
        Route::get('message-list-page', 'UserController@messageListPage')->name('message-list-page');


        Route::post('profile-update', 'UserController@profileUpdate')->name('profile-update');
        Route::post('message-mark-as-read', 'UserController@messageMarkAsRead')->name('message-mark-as-read');

    });
});

Route::group(['prefix' => 'tribe', 'as' => 'tribe.', 'namespace' => 'Tribe'], function(){
    Route::get('main', 'TribeController@mainPage')->name('main');
    Route::get('getTribePostings', 'TribeController@getTribePostings')->name('getTribePostings');
    Route::get('searchTribeFull', 'TribeController@searchTribeFull')->name('searchTribeFull');

    /**
     * Tribe functions that require login check.
     */
    Route::middleware(['logincheck'])->group(function () {
        Route::get('createForm', 'TribeController@createTribeForm')->name('createForm');
        Route::get('createPostingForm', 'TribeController@createPostingForm')->name('createPostingForm');
        Route::get('createProjectForm', 'TribeController@createProjectForm')->name('createProjectForm');
        Route::get('setting-main', 'TribeController@settingMain')->name('setting-main');
        Route::get('setting-profile', 'TribeController@settingMain')->name('setting-profile');


        Route::post('createPosting', 'TribeController@createPosting')->name('createPosting');
        Route::post('updatePosting', 'TribeController@updatePosting')->name('updatePosting');
        Route::post('deletePosting', 'TribeController@deletePosting')->name('deletePosting');

        Route::post('createTribe', 'TribeController@createTribe')->name('createTribe');
        Route::post('createProject', 'TribeController@createProject')->name('createProject');


        /**
         * Tribe setting functions (still need login check)
         */
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function(){
            Route::get('main', 'TribeSetController@settingMain')->name('main');
            Route::get('profile-edit', 'TribeSetController@profileEditForm')->name('profile-edit');
            Route::get('join-request', 'TribeSetController@joinRequest')->name('join-request');
            Route::get('project-list', 'TribeSetController@projectList')->name('project-list');

            Route::post('profile-update', 'TribeSetController@profileUpdate')->name('profile-update');

            Route::post('join-decline', 'TribeSetController@declineJoin')->name('join-decline');
            Route::post('join-accept', 'TribeSetController@acceptJoin')->name('join-accept');


        });

    });

    /**
     * Tribe functions that require login check for ajax calls.
     *
     */
    Route::middleware(['logincheck_ajax'])->group(function () {
        Route::post('requestJoin', 'TribeController@requestJoin')->name('requestJoin');
        Route::post('projectJoinRequest', 'TribeController@projectJoinRequest')->name('projectJoinRequest');
    });

});

resources/views/pages/sections/footer.blade.php
<footer class="text-center pb-5">
    <p>Created with &heartsuit; | Future Smith 2018 - <script>document.write(new Date().getFullYear());</script></p>
</footer>

resources/views/pages/sections/member-modal.blade.php
<script type="text/javascript">
  
  function onMemberClick(userId){
    
    $("#message-text").val("");

    var data = {
      "userId" : userId
    };

    $.ajax({
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
      },
      method: "GET",
      url: '{{ route('user.user-detail') }}',
      data: data
    }).done(function(result) {
      $("#memberModalLabel").text(result.user.name);
      $("#recipient-id").val(result.user.email);
      fillProfile(result);

    });

    $('#memberModal').modal('show');
  }

  /**
   * Fill profile modal with user detail
   * 
   * @param  {[type]} result [description]
   * @return {[type]}        [description]
   */
  function fillProfile(result){

    var interests = "";
    var length = result.user.interests.length;

    result.user.interests.forEach(function(element, index){
      interests += element.interest

      if(length != index+1){
        interests += ", ";
      } 
    });

    var profile = "";
    profile += "<b>Name:</b> " + result.user.name + "</br>";
    profile += "<b>Summary:</b> " + result.user.description + "</br>";
    profile += "<b>Interest:</b> " + interests + "</br>";
    profile += "<b>Suburb:</b> " + result.user.suburb + "</br>";
    profile += "<b>State:</b> " + result.user.state + "</br>";

    $("#profile-body").html(profile);

  }

</script>
<div class="modal fade" id="memberModal" tabindex="-1" role="dialog" aria-labelledby="memberModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="memberModalLabel" style="font-size: 20px;">New message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div id="accordion" role="tablist">
          <div class="card">
            <div class="card-header" role="tab" id="headingOne">
              <h3 class="mb-0">
                <a class="collapsed" data-toggle="collapse" href="#collapseOne" role="button" aria-expanded="true" aria-controls="collapseOne">
                  Profile
                </a>
              </h3>
            </div>
            <div id="collapseOne" class="collapse in" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
              <div class="card-body">
                <p id="profile-body">
                  Summary: Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. </br>
                  Name: name </br>
                  Interest: interest1, interest2, interest3 </br>
                  Suburb: suburb </br>
                  State: state </br>
                </p>
              </div>
            </div>
          </div>
          <hr/>
          <div class="card">
            <div class="card-header" role="tab" id="headingTwo">
              <h3 class="mb-0">
                <a class="collapsed" data-toggle="collapse" href="#collapseTwo" role="button" aria-expanded="false" aria-controls="collapseTwo">
                  Send Message
                </a>
              </h3>
            </div>
            <div id="collapseTwo" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
              <div class="card-body">
                {{-- <form method="post" action="{{ route('tribe.setting.profile-update') }}"> --}}
                  <div class="form-group">
                    <label for="recipient-name" class="col-form-label">Recipient:</label>
                    <input type="text" class="form-control" id="recipient-id" value="" disabled="true">
                  </div>
                  <div class="form-group">
                    <label for="message-text" class="col-form-label">Message:</label>
                    <textarea class="form-control" id="message-text"></textarea>
                  </div>
                {{-- </form>  --}}
                <button type="button" class="btn btn-primary" id="messageSendBtn" onclick="checkSendMessage();">Send message</button>
              </div>
            </div>
          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

resources/views/pages/sections/menu.blade.php
@php
if (!function_exists('classActivePath')) {
    function classActivePath($path)
    {
        $path = explode('.', $path);
        $segment = 1;
        foreach($path as $p) {
            if((request()->segment($segment) == $p) == false) {
                return '';
            }
            $segment++;
        }
        return 'active font-weight-bold underline';
    }
}
@endphp

<!--<link rel="stylesheet" href="{{ mix('/css/menu/style.css') }}">-->
<div class="row bg-theme-gray">
        <div class="col">
            <nav class="navbar navbar-expand-lg navbar-light bg-theme-gray">
                <a class="navbar-brand text-uppercase font-weight-bold" href="/">Future Smiths</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <span class="navbar-nav mr-auto"></span>
                    <ul class="navbar-nav">
                        <li class="nav-item pl-2 pr-2">
                            <a class="nav-link {!! classActivePath('front.aboutus') !!}" href="{{ route('front.aboutus') }}">About <span class="sr-only">(current)</span></a>
                        </li>

                    @if (Auth::check())
                        @if (Session::get("userCreatedTribesCount") > 0)
                            @php
                                $tribeId = Session::get("userTribes")[0]->tribe_id;
                            @endphp
                            <li class="nav-item pl-2 pr-2">
                                <a class="nav-link  {!! classActivePath('tribe.main') !!}" href="{{ route('tribe.main', ['tribe_id' => $tribeId]) }}">Your Tribe </a>
                            </li>
                        @else
                        <li class="nav-item pl-2 pr-2">
                            <a class="nav-link  {!! classActivePath('tribe.createForm') !!}" href="{{ route('tribe.createForm') }}">Tribes</a>
                        </li>
                        @endif
                    @elseif (!Auth::check())
                        <li class="nav-item pl-2 pr-2">
                            <a class="nav-link  {!! classActivePath('tribe.createForm') !!}" href="{{ route('tribe.createForm') }}">Tribes</a>
                        </li>
                    @endif
                        <li class="nav-item pl-2 pr-2">
                            <a class="nav-link  {!! classActivePath('front.projectSearchPage') !!}" href="{{ route('front.projectSearchPage') }}">Projects</a>
                        </li>
                    @if (Auth::check())
                        <li class="nav-item pl-2 pr-2">
                            <a class="nav-link  {!! classActivePath('user.profile-page') !!}" href="{{ route('user.profile-page') }}">Profile</a>
                        </li>
                        <li class="nav-item pl-2 pr-2">
                            <a class="btn btn-outline-dark white-hover  {!! classActivePath('auth.logout') !!}" href="{{ route('auth.logout') }}">Log out</a>
                        </li>
                    @else
                        <li class="nav-item pl-2 pr-2">
                            <a class="btn btn-outline-dark white-hover  {!! classActivePath('auth.loginForm') !!}" href="{{ route('auth.loginForm') }}"><b>Sign Up</b> or Log In</a>
                        </li>
                    @endif

                    </ul>
                </div>
            </nav>
        </div>
    </div>

resources/views/pages/sections/modal.blade.php
<!-- Select Message Modal -->
<div class="modal fade" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="messageModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="messageModalLabel">Message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="messageModalBody" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" id="confirmBtn" class="btn btn-primary" onclick="confirmClicked();">Confirm</button>
      </div>
    </div>
  </div>
</div>


<!-- Result Message Modal 1 -->
<div class="modal fade" id="resultMessageModal" tabindex="-1" role="dialog" aria-labelledby="resultMessageModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="resultMessageModalLabel">Message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="resultMessageModalBody" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

<!-- Result Message Modal 2 -->
<div class="modal fade" id="infoMessageModal" tabindex="-1" role="dialog" aria-labelledby="infoMessageModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="infoMessageModalLabel">Information Message</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div id="infoMessageModalBody" class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">OK</button>
      </div>
    </div>
  </div>
</div>

resources/views/pages/sections/profile-sidebar.blade.php
{{-- tribe setting sidebar nav --}}
<style type="text/css">
	.mini-submenu{
	  display:none;  
	  background-color: rgba(0, 0, 0, 0);  
	  border: 1px solid rgba(0, 0, 0, 0.9);
	  border-radius: 4px;
	  padding: 9px;  
	  /*position: relative;*/
	  width: 42px;

	}

	.mini-submenu:hover{
	  cursor: pointer;
	}

	.mini-submenu .icon-bar {
	  border-radius: 1px;
	  display: block;
	  height: 2px;
	  width: 22px;
	  margin-top: 3px;
	}

	.mini-submenu .icon-bar {
	  background-color: #000;
	}

	#slide-submenu{
	  background: rgba(0, 0, 0, 0.45);
	  display: inline-block;
	  padding: 0 8px;
	  border-radius: 4px;
	  cursor: pointer;
	}
</style>
<div class="col-md-3" style="height: 100vh;">
	<div class="col-md-12" style="padding-left: 0px; height: 100%;">
		<div class="col-sm-12 col-md-12 sidebar" style="border-right: solid; height: 100%; padding-left: 0px;">
		    <div class="mini-submenu">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		    </div>
		    <div class="list-group" style="height: 100%;">
		{{--         <span href="#" class="list-group-item active">
		            Submenu
		            <span class="pull-right" id="slide-submenu">
		                <i class="fa fa-times"></i>
		            </span>
		        </span> --}}
		        {{-- <a href="{{route('tribe.setting.main', ["tribe_id" => $tribe['tribe']->id])}}" class="list-group-item active" id="menu-main">
		            <i class="fa fa-home"></i> Main
		        </a> --}}
		        <a href="#" class="list-group-item" id="menu-join-request">
		            <i class="fa fa-comment-o"></i> Status <span class="badge"></span>
		        </a>
		        <a href="#" class="list-group-item" id="menu-profile-edit">
		            <i class="fa fa-edit"></i> Profile
		        </a>
		        <a href="#" class="list-group-item" id="menu-member">
		            <i class="fa fa-user"></i> Tribe
		        </a>
		        <a href="#" class="list-group-item" id="menu-project">
		            <i class="fa fa-folder-o"></i> Project <span class="badge"></span>
		        </a>
		    </div>        
		</div>
	</div>
</div>

<script type="text/javascript">
$(function(){

	$('#slide-submenu').on('click',function() {			        
        $(this).closest('.list-group').fadeOut('slide',function(){
        	$('.mini-submenu').fadeIn();	
        });
        
      });

	$('.mini-submenu').on('click',function(){		
        $(this).next('.list-group').toggle('slide');
        $('.mini-submenu').hide();
	});


	$(".list-group-item").each(function(){
		$(this).attr("class", "list-group-item");
	});

	// var selected = '{{$profile['selected']}}';
	// $("#menu-"+selected).attr("class", "list-group-item active");
})


</script>

resources/views/pages/sections/tribe-menu.blade.php
<style type="text/css">
  .navbar-nav {
    float: right;
    margin: 0;
  }
  .container{
    width: 100%;
  }
</style>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ route('tribe.main', ["tribe_id" => $tribe['tribe']->id]) }}">{{ $tribe['tribe']->name}}</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        {{-- <li class="active"><a href="#">Home</a></li>
        <li><a href="#about">About</a></li> --}}
        <li><a href="/">Home</a></li>
        @if ($tribe['isTribeMember'])
        {{-- <li role="presentation"><a href="#">Messages <span class="badge"></span></a></li> --}}
        <li role="presentation"><a href="{{route('tribe.setting.main', ["tribe_id" => $tribe['tribe']->id])}}">Manage</a></li>
        {{-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Setting <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Edit Tribe</a></li>
            <li><a href="#">More Features</a></li>
            <li><a href="#">Members</a></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Nav header</li>
            <li><a href="#">Separated link</a></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li> --}}
        @endif
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

resources/views/pages/sections/tribe-sidebar.blade.php
{{-- tribe setting sidebar nav --}}
<style type="text/css">
	.mini-submenu{
	  display:none;  
	  background-color: rgba(0, 0, 0, 0);  
	  border: 1px solid rgba(0, 0, 0, 0.9);
	  border-radius: 4px;
	  padding: 9px;  
	  /*position: relative;*/
	  width: 42px;

	}

	.mini-submenu:hover{
	  cursor: pointer;
	}

	.mini-submenu .icon-bar {
	  border-radius: 1px;
	  display: block;
	  height: 2px;
	  width: 22px;
	  margin-top: 3px;
	}

	.mini-submenu .icon-bar {
	  background-color: #000;
	}

	#slide-submenu{
	  background: rgba(0, 0, 0, 0.45);
	  display: inline-block;
	  padding: 0 8px;
	  border-radius: 4px;
	  cursor: pointer;
	}
</style>
<div class="col-md-3" style="height: 100vh;">
	<div class="col-md-12" style="padding-left: 0px; height: 100%;">
		<div class="col-sm-12 col-md-12 sidebar" style="border-right: solid; height: 100%; padding-left: 0px;">
		    <div class="mini-submenu">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		    </div>
		    <div class="list-group" style="height: 100%;">
		{{--         <span href="#" class="list-group-item active">
		            Submenu
		            <span class="pull-right" id="slide-submenu">
		                <i class="fa fa-times"></i>
		            </span>
		        </span> --}}
		        {{-- <a href="{{route('tribe.setting.main', ["tribe_id" => $tribe['tribe']->id])}}" class="list-group-item active" id="menu-main">
		            <i class="fa fa-home"></i> Main
		        </a> --}}
		        <a href="{{route('tribe.setting.join-request', ["tribe_id" => $tribe['tribe']->id])}}" class="list-group-item" id="menu-join-request">
		            <i class="fa fa-comment-o"></i> Join Request <span class="badge"></span>
		        </a>
		        <a href="{{route('tribe.setting.profile-edit', ["tribe_id" => $tribe['tribe']->id])}}" class="list-group-item" id="menu-profile-edit">
		            <i class="fa fa-edit"></i> Tribe Profile
		        </a>
		        <a href="#" class="list-group-item" id="menu-member">
		            <i class="fa fa-user"></i> Tribe Member
		        </a>
		        <a href="{{route('tribe.setting.project-list', ["tribe_id" => $tribe['tribe']->id])}}" class="list-group-item" id="menu-project-list">
		            <i class="fa fa-folder-o"></i> Project <span class="badge"></span>
		        </a>
		    </div>        
		</div>
	</div>
</div>

<script type="text/javascript">
$(function(){

	$('#slide-submenu').on('click',function() {			        
        $(this).closest('.list-group').fadeOut('slide',function(){
        	$('.mini-submenu').fadeIn();	
        });
        
      });

	$('.mini-submenu').on('click',function(){		
        $(this).next('.list-group').toggle('slide');
        $('.mini-submenu').hide();
	});


	$(".list-group-item").each(function(){
		$(this).attr("class", "list-group-item");
	});

	var selected = '{{$tribe['selected']}}';
	$("#menu-"+selected).attr("class", "list-group-item active");
})


</script>

resources/views/pages/sections/userprofile-sidebar.blade.php
{{-- tribe setting sidebar nav --}}
<style type="text/css">
	.mini-submenu{
	  display:none;  
	  background-color: rgba(0, 0, 0, 0);  
	  border: 1px solid rgba(0, 0, 0, 0.9);
	  border-radius: 4px;
	  padding: 9px;  
	  /*position: relative;*/
	  width: 42px;

	}

	.mini-submenu:hover{
	  cursor: pointer;
	}

	.mini-submenu .icon-bar {
	  border-radius: 1px;
	  display: block;
	  height: 2px;
	  width: 22px;
	  margin-top: 3px;
	}

	.mini-submenu .icon-bar {
	  background-color: #000;
	}

	#slide-submenu{
	  background: rgba(0, 0, 0, 0.45);
	  display: inline-block;
	  padding: 0 8px;
	  border-radius: 4px;
	  cursor: pointer;
	}
</style>
<div class="col-md-3" style="height: 100vh; margin-top: 7%;">
	<div class="col-md-12" style="padding-left: 0px; height: 100%;">
		<div class="col-sm-12 col-md-12 sidebar" style="border-right: solid; height: 100%; padding-left: 0px;">
		    <div class="mini-submenu">
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		    </div>
		    <div class="list-group" style="height: 100%;">
	{{-- 	        <span href="#" class="list-group-item active">
		            Submenu
		            <span class="pull-right" id="slide-submenu">
		                <i class="fa fa-times"></i>
		            </span>
		        </span> --}}
		        {{-- <a href="{{route('tribe.setting.main', ["tribe_id" => $tribe['tribe']->id])}}" class="list-group-item active" id="menu-main">
		            <i class="fa fa-home"></i> Main
		        </a> --}}
		        <a href="{{route('user.profile-page') }}" class="list-group-item" id="menu-profile-edit">
		            <i class="fa fa-user"></i> Profile
		        </a>
		        <a href="{{route('user.project-list-page') }}" class="list-group-item" id="menu-project-list">
		            <i class="fa fa-tasks"></i> Project
		        </a>
		        <a href="{{route('user.message-list-page')}}" class="list-group-item" id="menu-message-list">
		            <i class="fa fa-envelope"></i> Message <span class="badge">{{$msgCount}}</span>
		        </a>
		        <a href="#" class="list-group-item" id="menu-message-list">
		            <i class="fa fa-archive"></i> Message Archive
		        </a>
		    </div>        
		</div>
	</div>
</div>

<script type="text/javascript">
$(function(){

	$('#slide-submenu').on('click',function() {			        
        $(this).closest('.list-group').fadeOut('slide',function(){
        	$('.mini-submenu').fadeIn();	
        });
        
      });

	$('.mini-submenu').on('click',function(){		
        $(this).next('.list-group').toggle('slide');
        $('.mini-submenu').hide();
	});


	$(".list-group-item").each(function(){
		$(this).attr("class", "list-group-item");
	});

	var selected = '{{ $menu }}';
	$("#menu-"+selected).attr("class", "list-group-item active");
})


</script>