routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Front\FrontController@main');

// Common
Route::group(['prefix' => 'common', 'as' => 'common.', 'namespace' => 'Common'], function(){

    Route::get('redirectToLoginPageWithMessage', 'CommonController@redirectToLoginPageWithMessage')->name('redirectToLoginPageWithMessage');

});

// Route group for front page
Route::group(['prefix' => 'front', 'as' => 'front.', 'namespace' => 'Front'], function(){

    Route::get('getFrontTribes', 'FrontController@getFrontTribes')->name('getFrontTribes');
    Route::get('moreTribeSearch', 'FrontController@moreTribeSearchForm')->name('moreTribeSearch');
    Route::get('projectSearchPage', 'FrontController@projectSearchPage')->name('projectSearchPage');
    Route::get('searchProject', 'FrontController@searchProject')->name('searchProject');
    Route::get('viewProject', 'FrontController@viewProject')->name('viewProject');
    Route::get('contact', 'FrontController@contactPage')->name('contact');
    Route::get('aboutus', 'FrontController@aboutUs')->name('aboutus');
    Route::get('gettingStarted', 'FrontController@gettingStarted')->name('gettingStarted');

    Route::post('sendMessage', 'FrontController@sendMessage')->name('sendMessage');

});




// Route group for login page
Route::group(['prefix' => 'auth', 'as' => 'auth.', 'namespace' => 'Auth'], function () {

    //Users auth control
    Route::get('registrationForm', 'RegisterController@registrationForm')->name('registrationForm');
    Route::post('register', 'RegisterController@register')->name('register');


    //Login control
    Route::get('loginForm', 'LoginController@loginForm')->name('loginForm');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::post('login', 'LoginController@login')->name('login');

    // Route::get('users/{user}', 'UserController@show')->name('users.show');
    // Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    // Route::put('users/{user}', 'UserController@update')->name('users.update');
    // Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    // Route::get('permissions', 'PermissionController@index')->name('permissions');
    // Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
});

Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function(){

    Route::get('user-detail', 'UserController@userDetail')->name('user-detail');
    Route::post('sendMessage', 'UserController@sendMessage')->name('sendMessage');



    Route::middleware(['logincheck'])->group(function () {
        Route::get('profile-page', 'UserController@profilePage')->name('profile-page');
        Route::get('project-list-page', 'UserController@projectListPage')->name('project-list-page');
        Route::get('message-list-page', 'UserController@messageListPage')->name('message-list-page');


        Route::post('profile-update', 'UserController@profileUpdate')->name('profile-update');
        Route::post('message-mark-as-read', 'UserController@messageMarkAsRead')->name('message-mark-as-read');

    });
});

Route::group(['prefix' => 'tribe', 'as' => 'tribe.', 'namespace' => 'Tribe'], function(){
    Route::get('main', 'TribeController@mainPage')->name('main');
    Route::get('getTribePostings', 'TribeController@getTribePostings')->name('getTribePostings');
    Route::get('searchTribeFull', 'TribeController@searchTribeFull')->name('searchTribeFull');

    /**
     * Tribe functions that require login check.
     */
    Route::middleware(['logincheck'])->group(function () {
        Route::get('createForm', 'TribeController@createTribeForm')->name('createForm');
        Route::get('createPostingForm', 'TribeController@createPostingForm')->name('createPostingForm');
        Route::get('createProjectForm', 'TribeController@createProjectForm')->name('createProjectForm');
        Route::get('setting-main', 'TribeController@settingMain')->name('setting-main');
        Route::get('setting-profile', 'TribeController@settingMain')->name('setting-profile');


        Route::post('createPosting', 'TribeController@createPosting')->name('createPosting');
        Route::post('updatePosting', 'TribeController@updatePosting')->name('updatePosting');
        Route::post('deletePosting', 'TribeController@deletePosting')->name('deletePosting');

        Route::post('createTribe', 'TribeController@createTribe')->name('createTribe');
        Route::post('createProject', 'TribeController@createProject')->name('createProject');


        /**
         * Tribe setting functions (still need login check)
         */
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function(){
            Route::get('main', 'TribeSetController@settingMain')->name('main');
            Route::get('profile-edit', 'TribeSetController@profileEditForm')->name('profile-edit');
            Route::get('join-request', 'TribeSetController@joinRequest')->name('join-request');
            Route::get('project-list', 'TribeSetController@projectList')->name('project-list');

            Route::post('profile-update', 'TribeSetController@profileUpdate')->name('profile-update');

            Route::post('join-decline', 'TribeSetController@declineJoin')->name('join-decline');
            Route::post('join-accept', 'TribeSetController@acceptJoin')->name('join-accept');


        });

    });

    /**
     * Tribe functions that require login check for ajax calls.
     *
     */
    Route::middleware(['logincheck_ajax'])->group(function () {
        Route::post('requestJoin', 'TribeController@requestJoin')->name('requestJoin');
        Route::post('projectJoinRequest', 'TribeController@projectJoinRequest')->name('projectJoinRequest');
    });

});

app/Http/Controllers/Front/FrontController.php
<?php
namespace App\Http\Controllers\Front;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Auth;
use Mailgun\Mailgun;


use App\Helper\MemberHelper;

/**
 * Created by PhpStorm.
 * User: songminseok
 * Date: 27/7/17
 * Time: 9:39 PM
 */
class FrontController extends Controller
{



    /**
     * Search Tribe for the main front page.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Routing\ResponseFactory|\Symfony\Component\HttpFoundation\Response
     */
    public function main(Request $request){


        $tribes = DB::select("SELECT
                                    trb.id, trb.name, trb.summary, trb.topic1, trb.topic2, trb.image1, trb.topic1, trb.region, trb.country
                                    , (SELECT COUNT(user_id) FROM tribe_member mem WHERE mem.tribe_id = trb.id AND mem.active = 'Y') as member_no
                                FROM tribe trb
                                ORDER BY rand() LIMIT 10");

        $projects = DB::select("SELECT trp.id,trp.title,trp.description,trp.member_no,trp.topic,trp.location,trp.country,trp.created_by,trp.tribe_id,trp.updated_at,trp.created_at
                              FROM tribe_project trp
                              ORDER BY rand() LIMIT 10");


        $msgCount = 0;
        if (Auth::check()) {
            $msgCount = MemberHelper::countNewMessage($request->session()->get('email'));
        }


        return view('pages.front.front', ['tribes' => $tribes, 'projects' => $projects, 'msgCount'=>$msgCount]);
    }

    /**
     * [moreTribeSearchForm description]
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function moreTribeSearchForm(Request $request){

        return view('pages.front.tribe-search');
    }

    /**
     * About us
     *
     * @param  Reuqest $request [description]
     * @return [type]           [description]
     */
    public function aboutUs(Request $request){

        return view('pages.front.aboutus', ["videolink"=>"http://www.youtube.com/embed/FVpdUthXY2I"]);
    }

    /**
     * Getting started
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function gettingStarted(Request $request){
        return view('pages.front.getting-started');
    }

    /**
     * Move to project search page.
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function projectSearchPage(Request $request){
        $projects = DB::select("SELECT
            id, title, description, member_no, topic, location, country, created_by, tribe_id, updated_at, created_at
            FROM
                tribe_project
            ORDER BY rand() LIMIT 20");

        $interests = Config::get('code.interests');

        return view('pages.front.project-search', ['projects' => $projects, 'interests' => $interests, 'topic' => '']);
    }

    /**
     * Project search
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function searchProject(Request $request){


        $topic = $request['topic'];
        $area = $request['area'];

        $query = DB::table('tribe_project')
                    ->select(DB::raw('id, title, description, member_no,
                        topic, location, country, created_by,
                        tribe_id, updated_at, created_at' ) );

        if($topic != ''){
            $query->where('topic', $topic);
        }

        if($area != ''){
            $query->where('location', $area);
        }

        if($topic == '' && $area == ''){
            $query->inRandomOrder();
        }

        $projects = $query->get();

        $interests = Config::get('code.interests');

        return view('pages.front.project-search', ['projects' => $projects, 'interests' => $interests, 'topic' => $topic]);
    }

    /**
     * View project detail
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function viewProject(Request $request){

        $projectId = $request['projectId'];
        $project = DB::table('tribe_project')
            ->join('users', 'tribe_project.created_by', '=', 'users.email')
            ->select('tribe_project.id', 'tribe_project.title', 'tribe_project.description',
                     'users.name','tribe_project.topic', 'tribe_project.location', 'tribe_project.member_no',
                     'tribe_project.created_at')
            ->where('tribe_project.id', '=', $projectId)
            ->first();

        $userId = $request->session()->get('email');

        $userProjectStatus = DB::table('member_project')->where([
                                ['project_id', '=', $projectId],
                                ['user_id', '=', $userId],
                             ])->first();


        return view('pages.front.project-detail', ['project' => $project, 'userProjectStatus' => $userProjectStatus]);
    }

    /**
     * Move to the contact page.
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function contactPage(Request $request){
        return view('pages.front.contact');
    }

    /**
     * Send email via contact us.
     *
     * @param  Request $request [description]
     * @return [type]           [description]
     */
    public function sendMessage(Request $request){

        # Instantiate the client.
        $mgClient = new Mailgun(config('app.mailgun_secret'));
        $domain = "email.powerfulvoli.com";

        $message = "Sender: " . $request['name'] . "\n";
        $message .= "Phone: " . $request['tel'] . "\n\n";
        $message .= "Message: " . $request['message'];

        # Make the call to the client.
        $result = $mgClient->sendMessage($domain, array(
            'from'    => $request['sender-email'],
            'to'      => '<oasisers99@gmail.com>,<jacqui.storey89@gmail.com>',
            'subject' => '[Voli Postman] You have a new message from ' . $request['name'],
            'text'    => $message
        ));

        return redirect("/");
    }
}

resources/views/pages/front/project-detail.blade.php
@extends('layouts.common')

@section('title', config('app.name'))

@section('page-resources')
	<link rel="stylesheet" type="text/css" href="{{ mix('/css/front/front.css') }}">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	<style type="text/css">
		main{
			margin-top: 10%;
		}
	</style>
  <script type="text/javascript">

    /**
     * Show message modal
     * @return {[type]} [description]
     */
    function showMessageModal(){

      if(!('{{Auth::check()}}')){
        redirectIfNotLoggedIn();
      }else{
        $('#messageModalBody').text("Do you want to send a join request?");
        $('#messageModal').modal('show');
      }
    }

    /**
     * Send join request
     * @return {[type]} [description]
     */
    function confirmClicked(){
      var data = {
        'project_id' : '{{$project->id}}'
      };

     $.ajax({
        method: "POST",
        data: data,
        headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
        url: '{{ route('tribe.projectJoinRequest') }}'
      })
      .done(function(result){

        $('#messageModal').modal('hide');

        if(result.status == 'success'){
          $('#resultMessageModalBody').text("You've successfully sent the request.");
          location.reload();
        }else{
          $('#resultMessageModalBody').text("Sorry, there was some problem while sending the request. Please contact us.");
        }

         $('#resultMessageModal').modal('show');
      });
    }

    /**
     * Redirect if not logged in.
     * 
     * @param  {[type]} message [description]
     * @return {[type]}         [description]
     */
    function redirectIfNotLoggedIn(message){
      $('#infoMessageModalBody').text("Please login to send the request.");
      $('#infoMessageModal').modal('show');
      $('#infoMessageModal').on('hidden.bs.modal', function (e) {
        window.location.href = '{{route('common.redirectToLoginPageWithMessage')}}';
      });
    }
  </script>
@endsection

@section('body-content')
@include('pages.sections.modal')
<main role="main" class="container">

      <div class="row">

        <div class="col-sm-8 blog-main">

          <div class="blog-post">
            <h2 class="blog-post-title">{{$project->title}} </h2>
            <p class="blog-post-meta">{{ \Carbon\Carbon::parse($project->created_at)->format('d  M,  Y')}} by <a href="#">{{$project->name}}</a></p>

            <p>{{$project->description}} </p>
          </div><!-- /.blog-post -->

        

         {{--  <nav class="blog-pagination">
            <a class="btn btn-outline-primary" href="#">Older</a>
            <a class="btn btn-outline-secondary disabled" href="#">Newer</a>
          </nav> --}}

        </div><!-- /.blog-main -->

        <aside class="col-sm-3 ml-sm-auto blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            {{-- <h4>About</h4>
            <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p> --}}
          </div>
          <div class="sidebar-module">
            <h4>Details</h4>
            <ol class="list-unstyled">
              <li>Topic: {{$project->topic}}</a></li>
              <li>Location: {{$project->location}}</a></li>
              <li>Maximum project members: {{$project->member_no}}</a></li>
            </ol>
          </div>
          <div class="sidebar-module" style="margin-top: 20%;">
            <h4>Joined Members</h4>
            <ol class="list-unstyled">
            </ol>
          </div>
          <div class="sidebar-module" style="margin-top: 20%;">
            <h4>Share</h4>
            <ol class="list-unstyled">
              <li><a href="#">Twitter</a></li>
              <li><a href="#">Facebook</a></li>
            </ol>
          </div>
        </aside><!-- /.blog-sidebar -->

      </div><!-- /.row -->
      @isset($userProjectStatus)
        @if($userProjectStatus->status == 1)
          <button class="btn btn-primary" disabled="true" title="test">Request already sent</button>
        @elseif($userProjectStatus->status == 2)
          <button class="btn btn-primary" disabled="true" title="test">Already accepted</button>
        @else
          <button class="btn btn-primary" onclick="showMessageModal();">I want to join!</button>
        @endif
      @endisset
      @empty($userProjectStatus)
        <button class="btn btn-primary" onclick="showMessageModal();">I want to join!</button>
      @endempty
      <!-- Modal for message -->
    </main>
    
@endsection

resources/views/pages/front/projects.blade.php
<!-- Participate -->
<div class="row slick-row tribe-search" id="searchTribe">
    <div class="col text-center">
        <h2 class="font-weight-bold">Participate Now</h2>
        <p>You can join one of our many ongoing projects</p>
     </div>
</div>
<div class="row slick-row equal-height">
   <div class="col-12">
       <div class="slick-projects card-deck text-center">
           @foreach ($projects as $project)


           <div class="card" style="max-width:278px;">
            <img class="card-img-top" data-src="holder.js/100px180/" alt="100%x180" src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22278%22%20height%3D%22180%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20278%20180%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_161fa01f27f%20text%20%7B%20fill%3Argba(255%2C255%2C255%2C.75)%3Bfont-weight%3Anormal%3Bfont-family%3AHelvetica%2C%20monospace%3Bfont-size%3A14pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_161fa01f27f%22%3E%3Crect%20width%3D%22278%22%20height%3D%22180%22%20fill%3D%22%23777%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%22103.203125%22%20y%3D%2296.3%22%3E278x180%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E" data-holder-rendered="true" style="height: 180px; width: 100%; display: block;">
            <div class="card-body">
              <h5 class="card-title">{{ $project->title }}</h5>
            </div>
            <div class="card-footer">
              <a href="{{ route('front.viewProject', ["projectId" => $project->id]) }}" class="btn btn-outline-primary">Learn more</a>
            </div>
        </div>
           @endforeach

       </div>
   </div>
</div>
<!-- /. Participate -->
<script>
    $('document').ready(function(){
        //getFrontTribes();
        /**
         *  Retrieve tribes
         *
         */
        function getFrontTribes(){
            $.ajax({
                method: "GET",
                url: '{{ Route("front.getFrontTribes") }}'
            })
            .done(function(tribes){
                display(tribes);
            });
        }

        /**
         * Display results in the Tribes search section
         *
         * @param tribes
         */
        function display(tribes){
            if(tribes.length == 0){
                $("#search-message").text("Result not found.")
                return;
            }
        }
    });
</script>

resources/views/pages/front/tribe-search.blade.php
@extends('layouts.common')

@section('title', config('app.name'))

@section('page-resources')

<link rel="stylesheet" type="text/css" href="{{ mix('/css/front/front.css') }}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script>

    function validateAndSubmit(){
        //var topic = $("#search-interest").val();
        //var region = $("#search-area").val();
 
        // if(topic.trim() == '' && region.trim() == ''){
        //     $("#search-message").text("Please fill out interest or area.");
        //     return false;
        // }else{
        tribesearchform.submit();
        // }
        
    }
</script>
<style type="text/css">
    .tribe-search-text{
        position: absolute;
        border-radius:5px; 
        border-width: 2px;
        padding: 5px;
        font-size: 14px;
        color: #a6a6a6;
    }
    #search-interest{
        width:80%;
        right: 5%;
    }
    #search-area{
        width:40%;
    }
    #search-tribe-btn{
        margin-left: 45%;
    }
    #search-message{
        margin-top: 10px;
        text-align: center;
    }
    div.row.tribe-search{
        margin-top: 5%;
    }

    div.fh5co-blog-style-1.tribe-search{
        padding: 4em 0;
    }

    div.col-md-3.more-search{
        width: 20%;
    }
    .row.p-b.more-search{
        padding-bottom: 10px;
    }

    #search-result-hr{
        margin-top: 10px;
        margin-bottom: 20px;
    }
</style>
@endsection

@section('body-content')
<div class="fh5co-blog-style-1 tribe-search" id="searchTribe">
    <div class="container">
        <div class="row tribe-search">
            <div class="col-md-7 col-md-offset-3 text-center">
                <h2 class="fh5co-heading wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">Find your tribe!</h2>
                <p>We are a community of diverse tribes with different areas of interest. Together we create and run volunteering projects - leaving a lasting legacy in our communities. 
If you can’t see a tribe that suits you; <a href="{{ route('front.gettingStarted') }}">create a new one!</a><br/><br/>

 “A tribe is a group of people connected to one another… and connected to an idea. For millions of years, human beings have been part of one tribe or another. A group needs only two things to be a <b>tribe</b>: a shared interest and a way to communicate.” ― <b>Seth Godin</b>
</p>
            </div>
            <form class="tribe-search-form" method="GET" id="tribe-search" name='tribesearchform' action="{{ route('tribe.searchTribeFull') }}">
                {{ csrf_field() }}
                <div class="col-md-3 col-md-offset-3">
                    <select class="form-control select select-primary" data-toggle="select" id="search-interest" name="interest" style="    height: 40px; width: 260px;">
                    @foreach($interests as $idx=>$interest)
                    <option value="{{$interest}}" selected>{{$interest}}</option>
                    @endforeach
                    </select>
                </div>
                <div class="col-md-6">
                    <input type="text" class="tribe-search-text" id="search-area" name="area" placeholder="Area">
                    <input type="button" value="Search" class="btn btn-default" id="search-tribe-btn" onclick="validateAndSubmit();">
                </div>
            </form>
        </div>
        <div class="col-md-12 search-message" style="text-align: center;">
            <p id="search-message" style="font-size: 25px;"></p>
            <hr id="search-result-hr">
        </div>
        @if(count($tribes) === 0)
        <div class="col-md-12 result-message" style="text-align: center;">
            <p id="result-message" style="font-size: 25px;">No tribe found. Please search again.</p>
        </div>
        @endif
        @foreach ($tribes as $idx=>$tribe)
        @if(($idx + 1)%5 === 1)
        <div class="row p-b more-search">
        @endif
            {{-- @if(($idx + 1)%5 === 2 || ($idx + 1)%5 === 3 || ($idx + 1)%5 === 4) --}}
            <div class="col-md-3 more-search">
                <div class="fh5co-post wow fadeInLeft"  data-wow-duration="1s" data-wow-delay="1.1s">
                    <div class="fh5co-post-image">
                        <div class="fh5co-overlay"></div>
                        <div class="fh5co-category"><a href="#">{{$tribe->topic1}}</a></div>
                        <img src="/images/img_same_dimension_2.jpg" alt="Image" class="img-responsive">
                    </div>
                    <div class="fh5co-post-text">
                        <h3><a href="{{ route('tribe.main', ["tribe_id" => $tribe->id]) }}">{{$tribe->name}}</a></h3>
                        <p>{{ str_limit($tribe->summary, 150) }}</p>
                    </div>
                    <div class="fh5co-post-meta">
                        <a href="#"><i class="icon-group"></i> {{$tribe->member_no}}</a>
                        <a href="#"><i class="icon-map2"></i>{{$tribe->region}}</a>
                    </div>
                </div>
            </div>
            {{-- @endif --}}
        @if(($idx + 1)%5 === 0)
        </div> 
        @endif
        @endforeach

    </div>
</div>
@endsection

resources/views/pages/front/tribe.blade.php
<!-- Participate -->
<div class="row slick-row tribe-search pt-3" id="searchTribe">
   <div class="col-12 text-center">
       <h2 class="font-weight-bold">Join a tribe</h2>
                       <p>Meet like-minded eople in 'Tribes' or groups around you</p>
   </div>
   <div class="col-12">
       <div class="slick-tribe text-center">
           @foreach ($tribes as $tribe)
           <div class="pl-3 pr-3" style="max-width: 150px;">
                <a href="{{ route('tribe.main', ["tribe_id" => $tribe->id]) }}" href="//google.com">
                    <img class="rounded-circle img-fluid" src="//via.placeholder.com/150x150" alt="Category" width="100%" height="100%"/>
                    <p class="font-weight-bold mt-1">{{ $tribe->name }}</p>
                </a>
            </div>
           @endforeach
       </div>
   </div>
</div>
<!-- /. Participate -->
<div class="row pt-3 pb-3">
    <div class="col-12">
        <div class="text-center wow fadeInUp" data-wow-duration="1s" data-wow-delay="2s">
            <a href="{{ route('tribe.searchTribeFull') }}" class="btn btn-primary btn-lg">Find More Tribes</a>
        </div>
    </div>
</div>
<script>
    $('document').ready(function(){
        //getFrontTribes();
        /**
         *  Retrieve tribes
         *
         */
        function getFrontTribes(){
            $.ajax({
                method: "GET",
                url: '{{ Route("front.getFrontTribes") }}'
            })
            .done(function(tribes){
                display(tribes);
            });
        }

        /**
         * Display results in the Tribes search section
         *
         * @param tribes
         */
        function display(tribes){
            if(tribes.length == 0){
                $("#search-message").text("Result not found.")
                return;
            }
        }
    });
</script>

resources/views/pages/front/tribebackup.blade.php
<script>
    $('document').ready(function(){
        //getFrontTribes();
        /**
         *  Retrieve tribes
         *
         */
        function getFrontTribes(){
            $.ajax({
                method: "GET",
                url: '{{ Route("front.getFrontTribes") }}'
            })
            .done(function(tribes){
                display(tribes);
            });
        }

        /**
         * Display results in the Tribes search section
         *
         * @param tribes
         */
        function display(tribes){
            if(tribes.length == 0){
                $("#search-message").text("Result not found.")
                return;
            }
        }
    });
</script>

<!--
<div class="fh5co-blog-style-1 tribe-search" id="searchTribe">
    <div class="container">
        <div class="row p-b">
            @foreach ($tribes as $tribe)
            <div class="col-md-3 col-sm-6 col-xs-6 col-xxs-12 wow fadeInLeft">
                <div class="fh5co-post wow fadeInLeft"  data-wow-duration="1s" data-wow-delay="1.1s">
                    <div class="fh5co-post-image">
                        <div class="fh5co-overlay"></div>
                        <div class="fh5co-category"><a href="#">{{$tribe->topic1}}</a></div>
                        <img src="images/img_same_dimension_2.jpg" alt="Image" class="img-responsive">
                    </div>
                    <div class="fh5co-post-text">
                        <h3><a href="{{ route('tribe.main', ["tribe_id" => $tribe->id]) }}">{{$tribe->name}}</a></h3>
                        <p>{{ str_limit($tribe->summary, 200) }}</p>
                    </div>
                    <div class="fh5co-post-meta">
                        <a href="#"><i class="icon-group"></i> {{$tribe->member_no}}</a>
                        <a href="#"><i class="icon-map2"></i>{{$tribe->region}}, {{$tribe->country}}</a>
                    </div>
                </div>
            </div>
            @endforeach
        </div>

    </div>
</div>
-->

<!-- Participate -->
<div class="row slick-row tribe-search" id="searchTribe">
   <div class="col-12 text-center">
       <h2 class="font-weight-bold">Participate Now</h2>
       <p>You can join one of our many ongoing projects</p>
   </div>
   <div class="col-12">
       <div class="slick-projects card-group card-deck">
           @foreach ($tribes as $tribe)
               <div class="card">
                   <img class="card-img-top" src="images/img_same_dimension_2.jpg" alt="Card image cap" width="100%" height="100%"/>
                   <div class="card-footer align-self-center text-center w-100">
                       <h3>{{$tribe->name}}</h3>
                       <br/>
                       <a href="{{ route('tribe.main', ["tribe_id" => $tribe->id]) }}" class="btn btn-outline-primary">Learn More</a>
                   </div>
               </div>
           @endforeach
       </div>
   </div>
</div>
<!-- /. Participate -->
<div class="row pt-3 pb-3">
    <div class="col-12">
        <div class="text-center wow fadeInUp" data-wow-duration="1s" data-wow-delay="2s">
            <a href="{{ route('tribe.searchTribeFull') }}" class="btn btn-primary btn-lg">Find More Tribes</a>
        </div>
    </div>
</div>