routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Front\FrontController@main');

// Common
Route::group(['prefix' => 'common', 'as' => 'common.', 'namespace' => 'Common'], function(){

    Route::get('redirectToLoginPageWithMessage', 'CommonController@redirectToLoginPageWithMessage')->name('redirectToLoginPageWithMessage');

});

// Route group for front page
Route::group(['prefix' => 'front', 'as' => 'front.', 'namespace' => 'Front'], function(){

    Route::get('getFrontTribes', 'FrontController@getFrontTribes')->name('getFrontTribes');
    Route::get('moreTribeSearch', 'FrontController@moreTribeSearchForm')->name('moreTribeSearch');
    Route::get('projectSearchPage', 'FrontController@projectSearchPage')->name('projectSearchPage');
    Route::get('searchProject', 'FrontController@searchProject')->name('searchProject');
    Route::get('viewProject', 'FrontController@viewProject')->name('viewProject');
    Route::get('contact', 'FrontController@contactPage')->name('contact');
    Route::get('aboutus', 'FrontController@aboutUs')->name('aboutus');
    Route::get('gettingStarted', 'FrontController@gettingStarted')->name('gettingStarted');

    Route::post('sendMessage', 'FrontController@sendMessage')->name('sendMessage');

});




// Route group for login page
Route::group(['prefix' => 'auth', 'as' => 'auth.', 'namespace' => 'Auth'], function () {

    //Users auth control
    Route::get('registrationForm', 'RegisterController@registrationForm')->name('registrationForm');
    Route::post('register', 'RegisterController@register')->name('register');


    //Login control
    Route::get('loginForm', 'LoginController@loginForm')->name('loginForm');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::post('login', 'LoginController@login')->name('login');

    // Route::get('users/{user}', 'UserController@show')->name('users.show');
    // Route::get('users/{user}/edit', 'UserController@edit')->name('users.edit');
    // Route::put('users/{user}', 'UserController@update')->name('users.update');
    // Route::delete('users/{user}', 'UserController@destroy')->name('users.destroy');
    // Route::get('permissions', 'PermissionController@index')->name('permissions');
    // Route::get('permissions/{user}/repeat', 'PermissionController@repeat')->name('permissions.repeat');
});

Route::group(['prefix' => 'user', 'as' => 'user.', 'namespace' => 'User'], function(){

    Route::get('user-detail', 'UserController@userDetail')->name('user-detail');
    Route::post('sendMessage', 'UserController@sendMessage')->name('sendMessage');



    Route::middleware(['logincheck'])->group(function () {
        Route::get('profile-page', 'UserController@profilePage')->name('profile-page');
        Route::get('project-list-page', 'UserController@projectListPage')->name('project-list-page');
        Route::get('message-list-page', 'UserController@messageListPage')->name('message-list-page');


        Route::post('profile-update', 'UserController@profileUpdate')->name('profile-update');
        Route::post('message-mark-as-read', 'UserController@messageMarkAsRead')->name('message-mark-as-read');

    });
});

Route::group(['prefix' => 'tribe', 'as' => 'tribe.', 'namespace' => 'Tribe'], function(){
    Route::get('main', 'TribeController@mainPage')->name('main');
    Route::get('getTribePostings', 'TribeController@getTribePostings')->name('getTribePostings');
    Route::get('searchTribeFull', 'TribeController@searchTribeFull')->name('searchTribeFull');

    /**
     * Tribe functions that require login check.
     */
    Route::middleware(['logincheck'])->group(function () {
        Route::get('createForm', 'TribeController@createTribeForm')->name('createForm');
        Route::get('createPostingForm', 'TribeController@createPostingForm')->name('createPostingForm');
        Route::get('createProjectForm', 'TribeController@createProjectForm')->name('createProjectForm');
        Route::get('setting-main', 'TribeController@settingMain')->name('setting-main');
        Route::get('setting-profile', 'TribeController@settingMain')->name('setting-profile');


        Route::post('createPosting', 'TribeController@createPosting')->name('createPosting');
        Route::post('updatePosting', 'TribeController@updatePosting')->name('updatePosting');
        Route::post('deletePosting', 'TribeController@deletePosting')->name('deletePosting');

        Route::post('createTribe', 'TribeController@createTribe')->name('createTribe');
        Route::post('createProject', 'TribeController@createProject')->name('createProject');


        /**
         * Tribe setting functions (still need login check)
         */
        Route::group(['prefix' => 'setting', 'as' => 'setting.'], function(){
            Route::get('main', 'TribeSetController@settingMain')->name('main');
            Route::get('profile-edit', 'TribeSetController@profileEditForm')->name('profile-edit');
            Route::get('join-request', 'TribeSetController@joinRequest')->name('join-request');
            Route::get('project-list', 'TribeSetController@projectList')->name('project-list');

            Route::post('profile-update', 'TribeSetController@profileUpdate')->name('profile-update');

            Route::post('join-decline', 'TribeSetController@declineJoin')->name('join-decline');
            Route::post('join-accept', 'TribeSetController@acceptJoin')->name('join-accept');


        });

    });

    /**
     * Tribe functions that require login check for ajax calls.
     *
     */
    Route::middleware(['logincheck_ajax'])->group(function () {
        Route::post('requestJoin', 'TribeController@requestJoin')->name('requestJoin');
        Route::post('projectJoinRequest', 'TribeController@projectJoinRequest')->name('projectJoinRequest');
    });

});

resources/views/pages/login/login.blade.php
@extends('layouts.common')

@section('title','Login')

@section('page-resources')
<link rel="stylesheet" type="text/css" href="{{ mix('/css/auth/style.css') }}">
@endsection


@section('body-content')
<div class="login-page">
	<div class="form">
	  	<h1 class="loginMainMessage">Welcome!</h1>
		<form class="login-form" method="post" id="login" action="{{ route('auth.login') }}">
			{{ csrf_field() }}
			<input type="text" name="email" placeholder="Email" required="required" />
			<input type="password" name="password" placeholder="Password" required="required" />
			<button>LOGIN</button>
			<p class="message">Not registered? <a href="{{ route('auth.registrationForm') }}">Create an account</a></p>
		</form>
		{{-- When redirected from Create Tribe --}}
		@if(session()->has('warning'))
		<div class="alert alert-danger">
		 	<ul>
			 	<li style="color: white;">{!! session()->get('warning') !!}</li>
		  	</ul>
	  	</div>
	  	@endif
	  	{{-- Login error messages --}}
	  	@if ($errors->any())
		  <div class="alert alert-danger">
			  <ul>
				  @foreach ($errors->all() as $error)
					  <li>{{ $error }}</li>
				  @endforeach
			  </ul>
		  </div>
	  	@endif
	</div>
</div>
@endsection

resources/views/pages/login/login_backup.blade.php
@extends('layouts.app')

@section('title','Login')

@section('page-resources')


  	<link rel="stylesheet" type="text/css" href="{{ mix('/css/auth/style.css') }}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.js"></script>
	<style>
		/* NOTE: The styles were added inline because Prefixfree needs access to your styles and they must be inlined if they are on local disk! */
		@import url(https://fonts.googleapis.com/css?family=Open+Sans);
		.btn { display: inline-block; *display: inline; *zoom: 1; padding: 4px 10px 4px; margin-bottom: 0; font-size: 13px; line-height: 18px; color: #333333; text-align: center;text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75); vertical-align: middle; background-color: #f5f5f5; background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6); background-image: -ms-linear-gradient(top, #ffffff, #e6e6e6); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6)); background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6); background-image: -o-linear-gradient(top, #ffffff, #e6e6e6); background-image: linear-gradient(top, #ffffff, #e6e6e6); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#ffffff, endColorstr=#e6e6e6, GradientType=0); border-color: #e6e6e6 #e6e6e6 #e6e6e6; border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25); border: 1px solid #e6e6e6; -webkit-border-radius: 4px; -moz-border-radius: 4px; border-radius: 4px; -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05); cursor: pointer; *margin-left: .3em; }
		.btn:hover, .btn:active, .btn.active, .btn.disabled, .btn[disabled] { background-color: #e6e6e6; }
		.btn-large { padding: 9px 14px; font-size: 15px; line-height: normal; -webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px; }
		.btn:hover { color: #333333; text-decoration: none; background-color: #e6e6e6; background-position: 0 -15px; -webkit-transition: background-position 0.1s linear; -moz-transition: background-position 0.1s linear; -ms-transition: background-position 0.1s linear; -o-transition: background-position 0.1s linear; transition: background-position 0.1s linear; }
		.btn-primary, .btn-primary:hover { text-shadow: 0 -1px 0 rgba(0, 0, 0, 0.25); color: #ffffff; }
		.btn-primary.active { color: rgba(255, 255, 255, 0.75); }
		.btn-primary { background-color: #4a77d4; background-image: -moz-linear-gradient(top, #6eb6de, #4a77d4); background-image: -ms-linear-gradient(top, #6eb6de, #4a77d4); background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#6eb6de), to(#4a77d4)); background-image: -webkit-linear-gradient(top, #6eb6de, #4a77d4); background-image: -o-linear-gradient(top, #6eb6de, #4a77d4); background-image: linear-gradient(top, #6eb6de, #4a77d4); background-repeat: repeat-x; filter: progid:dximagetransform.microsoft.gradient(startColorstr=#6eb6de, endColorstr=#4a77d4, GradientType=0);  border: 1px solid #3762bc; text-shadow: 1px 1px 1px rgba(0,0,0,0.4); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.5); }
		.btn-primary:hover, .btn-primary:active, .btn-primary.active, .btn-primary.disabled, .btn-primary[disabled] { filter: none; background-color: #4a77d4; }
		.btn-block { width: 100%; display:block; }

		* { -webkit-box-sizing:border-box; -moz-box-sizing:border-box; -ms-box-sizing:border-box; -o-box-sizing:border-box; box-sizing:border-box; }

		html { width: 100%; height:100%; overflow:hidden; }

		body {
			width: 100%;
			height:100%;
			font-family: 'Open Sans', sans-serif;
			background: #092756;
			background: -moz-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%),-moz-linear-gradient(top,  rgba(57,173,219,.25) 0%, rgba(42,60,87,.4) 100%), -moz-linear-gradient(-45deg,  #670d10 0%, #092756 100%);
			background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -webkit-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -webkit-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
			background: -o-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -o-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -o-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
			background: -ms-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), -ms-linear-gradient(top,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), -ms-linear-gradient(-45deg,  #670d10 0%,#092756 100%);
			background: -webkit-radial-gradient(0% 100%, ellipse cover, rgba(104,128,138,.4) 10%,rgba(138,114,76,0) 40%), linear-gradient(to bottom,  rgba(57,173,219,.25) 0%,rgba(42,60,87,.4) 100%), linear-gradient(135deg,  #670d10 0%,#092756 100%);
			filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#3E1D6D', endColorstr='#092756',GradientType=1 );
		}
		.login {
			position: absolute;
			top: 50%;
			left: 50%;
			margin: -150px 0 0 -150px;
			width:300px;
			height:300px;
		}
		.login h1 { color: #fff; text-shadow: 0 0 10px rgba(0,0,0,0.3); letter-spacing:1px; text-align:center; }

		input {
			width: 100%;
			margin-bottom: 10px;
			background: rgba(0,0,0,0.3);
			border: none;
			outline: none;
			padding: 10px;
			font-size: 13px;
			color: #fff;
			text-shadow: 1px 1px 1px rgba(0,0,0,0.3);
			border: 1px solid rgba(0,0,0,0.3);
			border-radius: 4px;
			box-shadow: inset 0 -5px 45px rgba(100,100,100,0.2), 0 1px 1px rgba(255,255,255,0.2);
			-webkit-transition: box-shadow .5s ease;
			-moz-transition: box-shadow .5s ease;
			-o-transition: box-shadow .5s ease;
			-ms-transition: box-shadow .5s ease;
			transition: box-shadow .5s ease;
		}
		input:focus { box-shadow: inset 0 -5px 45px rgba(100,100,100,0.4), 0 1px 1px rgba(255,255,255,0.2); }
	</style>


	<script type="text/javascript">
		$(document).ready({
			
		});
	</script>

@endsection

@section('body-content')
  <div class="login">
	  <h1>Welcome back!</h1>
	  @if(session()->has('warning'))
	  <div class="alert alert-danger">
		  <ul>
			  <li style="color: white;">{!! session()->get('warning') !!}</li>
		  </ul>
	  </div>
	  @endif
	  <form method="post" id="login" action="{{ route('auth.login') }}">
			{{ csrf_field() }}
	    	<input type="text" name="email" placeholder="Email" required="required" />
	        <input type="password" name="password" placeholder="Password" required="required" />
	        <button type="submit" class="btn btn-primary btn-block btn-large">Login</button>
	  </form>
	  @if ($errors->any())
		  <div class="alert alert-danger">
			  <ul>
				  @foreach ($errors->all() as $error)
					  <li style="color: white;">{{ $error }}</li>
				  @endforeach
			  </ul>
		  </div>
	  @endif
	</div>

@endsection